### ISSUE TITLE
Also export `sendErrorToSlack` function

### ISSUE THREAD

**Issue by mgcrea** [chunkai1312/express-error-slack#1]
Would be great to also export `sendErrorToSlack` function in case we would like to manually send an error (outside of express) to slack, using the same nice formatting.

Thanks!

**Comment by chunkai1312** [comment]
Thanks for your feedback! I have published the new version of this module. If you have any ideas, feel free to make pull request for any additional features.

**Comment by mgcrea** [comment]
Awesome, thanks!
