### ISSUE TITLE
Is README.md  correct? actually updated ?

### ISSUE THREAD

**Issue by tomlla** [chunkai1312/express-error-slack#2]
I read README.md and append this code to my node  app.

```
const express = require('express');
const errorToSlack = require('express-error-slack');

const server = express();
server.use(errorToSlack({ webhookUri: config.slack.webhookUri }))
```

and When I started my node app, I got this error,

```
TypeError: errorToSlack is not a function
```

I tried to debug  with `node's debugger`.
Here is repl log.

```
const errorToSlack = require('express-error-slack');

> errorToSlack
{ sendErrorToSlack: , default: , __esModule: true }
> errorToSlack.default
[Function]
> errorToSlack.sendErrorToSlack
[Function: sendErrorToSlack]
```

I think ` server.use(errorToSlack({ webhookUri: ... }))` is not correct, and I have to use `errorToSlack.default()`or `errorToSlack.sendErrorToSlack`

Does anyone tell me how to use `express-error-slack`?

**Comment by chunkai1312** [comment]
I have released the new version of the module to fix this error.
Thank you!
