### ISSUE TITLE
Show req.headers['x-forwarded-for'] || req.connection.remoteAddress

### ISSUE THREAD

**Issue by christiaanwesterbeek** [chunkai1312/express-error-slack#3]
Almost everybody is running his web app behind a proxy. They (or at least I) will most likely be interested in the remote client address and not of the proxy the web app is behind of.

I recommend changing the getRemoteAddress  function in here to use:

`req.headers['x-forwarded-for']`

https://github.com/chunkai1312/express-error-slack/blob/master/src/sendErrorToSlack.js#L4-L9 

https://stackoverflow.com/questions/10849687/express-js-how-to-get-remote-client-address

**Comment by christiaanwesterbeek** [comment]
See https://github.com/chunkai1312/express-error-slack/pull/4

**Comment by chunkai1312** [comment]
Thanks for your suggestion, and `express-error-slack@1.1.0` has been published.
